#!/usr/bin/env bash

nick=$(tr -dc 'a-zA-Z0-9 *<>+_-' <<< "$1")
[[ "$nick" == "phrik" ]] && exit
mesg=$(tr -dc 'a-zA-Z0-9 *<>+_-' <<< "$2")
ircd=$(tr -dc 'a-zA-Z0-9 *<>+_-' <<< "$3")
netw=$(tr -dc 'a-zA-Z0-9 *<>+_-' <<< "$4")
chan=$(tr -dc 'a-zA-Z0-9 *<>+_-' <<< "$5")
self=$(tr -dc 'a-zA-Z0-9 *<>+_-' <<< "$6")

#set -x
read -r cmd extra <<< "$mesg"
if [[ "$mesg" =~ .*\>.+ ]]; then
  read -r nicks <<< "${extra#*>}"
  read -r extra <<< "${extra%>*}"
fi

case "$cmd" in
  grep)
    read -r target word <<< "$extra"
    [[ -z "$target" ]] && exit
    grep "$target" lista &> /dev/null && exit
    temp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
    {
      if [[ "$target" != '*' ]]; then
        cut -c 18- "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -Ei "^<$target> .*$word"
      else
        cut -c 18- "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -i "$word" |  \
        grep -ivf lista     # FIXME : this removes <nick> , not only ^<nick>
      fi
    } | grep -Ev "^<\w+> \." > "$temp"
    [[ "$nick" == "$target" ]] && sed "$ d" -i "$temp"
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    if (( $(wc -l <"$temp") > 1 )); then
      echo -n "http://arin.ga/";
      sed -r "s/.*(.{6})$/\\1/" <<< "$temp"
      chmod a+r "$temp"
    else
      cat "$temp"
    fi
    ;;
  nolog)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    grep "$nick" lista &> /dev/null || echo "^<$nick>" >> lista
    ;;
  log)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    grep "$nick" lista &> /dev/null && sed -i "/<$nick>/ d" lista
    ;;
  source)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    echo https://github.com/izabera/archlog
    ;;
  help)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    echo ".grep nick frase  Se nick == * cerca tra i nick di tutti.  Privacy on: .nolog, off: .log"
    echo ".rank [nick]   Se non inserisci un nick, mostra il tuo rank. Se nick == * mostra la classifica"
    echo "per vedere il sorgente, visita https://github.com/izabera/archlog"
    ;;
  hidden)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    echo -n "questi utenti non vogliono farsi loggare: "
    cat lista | tr -s '\n' ' ' | tr -d '<>' | sed 's/ \+/ /g'
    echo
    ;;
  rank)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    [[ -z "$extra" ]] && extra="$nick"
    temp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
    if [[ "$extra" != '*' ]]; then
      {
        sed -r "s/^.{17}//g" "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -Ei "^<[^ ]* (($extra ?(\+\+|--))|((\+\+|--) ?$extra));?$" |  \
        grep -Evi "^<$extra>"
      }  > "$temp"
      piu=$(grep "\+\+" "$temp" | wc -l | tr -d '\n')
      meno=$(grep -- "--" "$temp" | wc -l | tr -d '\n')
      tot=$(( piu - meno ))
      [[ -n "$nicks" ]] && echo -n "$nicks: "
      echo "rank di $extra: ++ = $piu, -- = $meno, totale = $tot"
    else
      {
        cut -c 18- "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -Ei "^<[^ ]* ((\w+ ?(\+\+|--))|((\+\+|--) ?\w+));?$" |  \
        tr -d ' ' |  \
        sed -r -e 's/(\w*)(\+\+|--)/\2\1/g' -e 's/;$//' |  \
        grep -Evi "<([^>]*)>..\1" |  \
        sed -r 's/^<.*>//' |  \
        tr A-Z a-z |  \
        sort |  \
        uniq -c 
      }  > "$temp"
      nicklist=$(cut -c 11- "$temp" | sort -u)
      tempp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
      while read nickname; do
        piu=$(grep "\+\+$nickname" "$temp")
        if [[ "x$piu" == "x" ]]; then
          piu=0
        else
          piu=$(echo "$piu" | awk '{print $1}')
        fi
        meno=$(grep -- "--$nickname" "$temp" | awk '{print $1}')
        if [[ "x$meno" == "x" ]]; then
          meno=0
        else
          meno=$(echo "$meno" | awk '{print $1}')
        fi
        tot=$(( piu - meno ))
        echo "$tot $nickname (++ = $piu, -- = $meno)" >> "$tempp"
      done <<< "$nicklist"
      sort -nr "$tempp" > "$temp"
      rm "$tempp"
      [[ -n "$nicks" ]] && echo -n "$nicks: "
      echo "http://arin.ga/${temp:(-6)}";
      chmod a+r "$temp"
    fi
    ;;
  tail)
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    [[ -z "$extra" ]] && extra=5
    numbers="^[1-9][0-9]*[ogsma]?$"
    [[ $extra =~ $numbers ]] || extra=5
    temp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
    {
      case "${extra:(-1)}" in
        o)
          pattern=$(date -d "${extra:0:(-1)} hour ago" '+%Y-%m-%d%H:%M')
          line=$(awk -v "t=$pattern" '$1$2 > t { print NR; exit }' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out")
          sed -n "$line"',$p' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out"
          ;;
        g)
          pattern=$(date -d "${extra:0:(-1)} day ago" '+%Y-%m-%d%H:%M')
          line=$(awk -v "t=$pattern" '$1$2 > t { print NR; exit }' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out")
          sed -n "$line"',$p' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out"
          ;;
        s)
          pattern=$(date -d "${extra:0:(-1)} week ago" '+%Y-%m-%d%H:%M')
          line=$(awk -v "t=$pattern" '$1$2 > t { print NR; exit }' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out")
          sed -n "$line"',$p' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out"
          ;;
        m)
          pattern=$(date -d "${extra:0:(-1)} month ago" '+%Y-%m-%d%H:%M')
          line=$(awk -v "t=$pattern" '$1$2 > t { print NR; exit }' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out")
          sed -n "$line"',$p' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out"
          ;;
        a)
          pattern=$(date -d "${extra:0:(-1)} year ago" '+%Y-%m-%d%H:%M')
          line=$(awk -v "t=$pattern" '$1$2 > t { print NR; exit }' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out")
          sed -n "$line"',$p' "$HOME/ircbot/irc.freenode.net/#archlinux.it/out"
          ;;
        *)
          tempp=$((extra + 1))
          echo "$extra" >&2
          tail -n "$((extra + 1))" "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
          head -n "$extra"
          ;;
      esac
    } > "$temp"
    while read hidden ; do
      [[ "x$hidden" != "x" ]] && sed -r "s/^(.{17})($hidden).*$/\1\2----------------------------/" -i "$temp"
    done < lista
    if [[ "$extra" == 1 ]] ; then
      cat "$temp"
      rm "$temp"
    else 
      echo "http://arin.ga/${temp:(-6)}"
      chmod a+r "$temp"
    fi
    ;;

esac

