#!/usr/bin/env bash

nick=$(tr -dc 'a-zA-Z0-9 *+_-' <<< "$1")
mesg=$(tr -dc 'a-zA-Z0-9 *+_-' <<< "$2")
ircd=$(tr -dc 'a-zA-Z0-9 *+_-' <<< "$3")
netw=$(tr -dc 'a-zA-Z0-9 *+_-' <<< "$4")
chan=$(tr -dc 'a-zA-Z0-9 *+_-' <<< "$5")
self=$(tr -dc 'a-zA-Z0-9 *+_-' <<< "$6")

read -r cmd extra <<< "$mesg"
if [[ "$mesg" =~ .*\>.+ ]]; then
  read -r nicks <<< "${extra#*>}"
  read -r extra <<< "${extra%>*}"
fi

case "$cmd" in
  grep)
    read -r target word <<< "$extra"
    [[ -z "$target" ]] && exit
    grep "$target" lista &> /dev/null && exit
    temp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
    {
      if [[ "$target" != '*' ]]; then
        sed -r "s/^.{17}//g" "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -Ei "^<$target> .*$word"
      else
        sed -r "s/^.{17}//g" "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -i "$word" |  \
        grep -Fivf lista
      fi
    } | grep -Ev "^<\w+> \." > "$temp"
    [[ "$nick" == "$target" ]] && sed "$ d" -i "$temp"
    [[ -n "$nicks" ]] && echo -n "$nicks: "
    if (( $(wc -l <"$temp") > 1 )); then
      echo -n "http://arin.ga/"; sed -r "s/.*(.{6})$/\\1/" <<< "$temp"
      chmod a+r "$temp"
    else
      cat "$temp"
    fi
    ;;
  nolog)
    grep "$nick" lista &> /dev/null || echo "<$nick>" >> lista
    ;;
  log)
    grep "$nick" lista &> /dev/null && sed -i -r "s/^<$nick>$//" lista
    ;;
  source)
    echo https://github.com/izabera/archlog
    ;;
  help)
    echo "cerca nella cronologia con .grep nick frase"
    echo "per non mostrare cose dette da te, .nolog    per mostrarle di nuovo, .log"
    echo "per vedere il sorgente, visita https://github.com/izabera/archlog"
    ;;
  hidden)
    echo -n "questi utenti non vogliono farsi loggare: "
    cat lista | tr -s '\n' ' ' | tr -d '<>' | sed 's/ \+/ /g'
    echo
    ;;
  rank)
    [[ -z "$extra" ]] && extra="$nick"
    temp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
    if [[ "$extra" != '*' ]]; then
      {
        sed -r "s/^.{17}//g" "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -Ei "^<.*?> (($extra ?(\+\+|--))|((\+\+|--) ?$extra));?$"
      }  > "$temp"
      piu=$(grep "\+\+" "$temp" | wc -l | tr -d '\n')
      meno=$(grep -- "--" "$temp" | wc -l | tr -d '\n')
      tot=$(( piu - meno ))
      [[ -n "$nicks" ]] && echo -n "$nicks: "
      echo "rank di $extra: ++ = $piu, -- = $meno, totale = $tot"
    else
      {
        sed -r "s/^.{17}[^ ]* //g" "$HOME/ircbot/irc.freenode.net/#archlinux.it/out" |  \
        grep -Ei "^((\w+ ?(\+\+|--))|((\+\+|--) ?\w+));?$" |  \
        tr -d ' ' |  \
        sed -r -e 's/(\w*)(\+\+|--)/\2\1/g' -e 's/;$//' |  \
        tr A-Z a-z |  \
        sort |  \
        uniq -c 
      }  > "$temp"
      nicklist=$(cut -c 11- "$temp" | sort -u)
      tempp=$(mktemp -p /var/www/arin.ga/public_html XXXXXX)
      while read nickname; do
        piu=$(grep "\+\+$nickname" "$temp")
        if [[ "x$piu" == "x" ]]; then
          piu=0
        else
          piu=$(echo "$piu" | awk '{print $1}')
        fi
        meno=$(grep -- "--$nickname" "$temp" | awk '{print $1}')
        if [[ "x$meno" == "x" ]]; then
          meno=0
        else
          meno=$(echo "$meno" | awk '{print $1}')
        fi
        tot=$(( piu - meno ))
        echo "$tot $nickname (++ = $piu, -- = $meno)" >> "$tempp"
      done <<< "$nicklist"
      sort -nr "$tempp" > "$temp"
      rm "$tempp"
      [[ -n "$nicks" ]] && echo -n "$nicks: "
      echo -n "http://arin.ga/"; sed -r "s/.*(.{6})$/\\1/" <<< "$temp"
      chmod a+r "$temp"
    fi
    ;;

esac

